<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LTCH-5CD105HTG9" name="Test" tests="9" failures="4" timestamp="8 Apr 2021 14:08:23 GMT" time="19.604" errors="0">
  <testcase name="getTheListOfRulesForARevision_status200" time="3.806" classname="restassured.automation.testcases.Restassured_Automation_Rules"/>
  <testcase name="postCreateANewRuleSet_status200" time="2.048" classname="restassured.automation.testcases.Restassured_Automation_Rules"/>
  <testcase name="postCreateANewRuleSet_status400" time="1.65" classname="restassured.automation.testcases.Restassured_Automation_Rules"/>
  <testcase name="postCreateANewRuleSet_status409" time="2.051" classname="restassured.automation.testcases.Restassured_Automation_Rules">
    <failure type="java.lang.AssertionError" message="expected [409] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [409] but found [500]
	at restassured.automation.testcases.Restassured_Automation_Rules.postCreateANewRuleSet_status409(Restassured_Automation_Rules.java:354)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- postCreateANewRuleSet_status409 -->
  <testcase name="putUpdateANewRuleSet_status200" time="2.03" classname="restassured.automation.testcases.Restassured_Automation_Rules">
    <failure type="java.lang.AssertionError" message="expected [200] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
	at restassured.automation.testcases.Restassured_Automation_Rules.putUpdateANewRuleSet_status200(Restassured_Automation_Rules.java:455)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- putUpdateANewRuleSet_status200 -->
  <testcase name="putUpdateANewRuleSet_status400" time="2.056" classname="restassured.automation.testcases.Restassured_Automation_Rules"/>
  <testcase name="putUpdateANewRuleSet_status409" time="2.204" classname="restassured.automation.testcases.Restassured_Automation_Rules">
    <failure type="java.lang.AssertionError" message="expected [409] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [409] but found [200]
	at restassured.automation.testcases.Restassured_Automation_Rules.putUpdateANewRuleSet_status409(Restassured_Automation_Rules.java:660)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- putUpdateANewRuleSet_status409 -->
  <testcase name="deleteARuleSet_status204" time="2.102" classname="restassured.automation.testcases.Restassured_Automation_Rules"/>
  <testcase name="deleteARuleSet_status400" time="1.561" classname="restassured.automation.testcases.Restassured_Automation_Rules">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at restassured.automation.testcases.Restassured_Automation_Rules.deleteARuleSet_status400(Restassured_Automation_Rules.java:781)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- deleteARuleSet_status400 -->
</testsuite> <!-- Test -->
