<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="9" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="19604" started-at="2021-04-08T14:08:03Z" finished-at="2021-04-08T14:08:23Z">
    <groups>
      <group name="IntegrationTests">
        <method signature="Restassured_Automation_Rules.deleteARuleSet_status204()[pri:8, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="deleteARuleSet_status204" class="restassured.automation.testcases.Restassured_Automation_Rules"/>
        <method signature="Restassured_Automation_Rules.deleteARuleSet_status400()[pri:9, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="deleteARuleSet_status400" class="restassured.automation.testcases.Restassured_Automation_Rules"/>
        <method signature="Restassured_Automation_Rules.getTheListOfRulesForARevision_status200()[pri:1, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="getTheListOfRulesForARevision_status200" class="restassured.automation.testcases.Restassured_Automation_Rules"/>
        <method signature="Restassured_Automation_Rules.postCreateANewRuleSet_status200()[pri:2, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="postCreateANewRuleSet_status200" class="restassured.automation.testcases.Restassured_Automation_Rules"/>
        <method signature="Restassured_Automation_Rules.postCreateANewRuleSet_status400()[pri:3, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="postCreateANewRuleSet_status400" class="restassured.automation.testcases.Restassured_Automation_Rules"/>
        <method signature="Restassured_Automation_Rules.postCreateANewRuleSet_status409()[pri:4, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="postCreateANewRuleSet_status409" class="restassured.automation.testcases.Restassured_Automation_Rules"/>
        <method signature="Restassured_Automation_Rules.putUpdateANewRuleSet_status200()[pri:5, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="putUpdateANewRuleSet_status200" class="restassured.automation.testcases.Restassured_Automation_Rules"/>
        <method signature="Restassured_Automation_Rules.putUpdateANewRuleSet_status400()[pri:6, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="putUpdateANewRuleSet_status400" class="restassured.automation.testcases.Restassured_Automation_Rules"/>
        <method signature="Restassured_Automation_Rules.putUpdateANewRuleSet_status409()[pri:7, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="putUpdateANewRuleSet_status409" class="restassured.automation.testcases.Restassured_Automation_Rules"/>
      </group> <!-- IntegrationTests -->
    </groups>
    <test name="Test" duration-ms="19604" started-at="2021-04-08T14:08:03Z" finished-at="2021-04-08T14:08:23Z">
      <class name="restassured.automation.testcases.Restassured_Automation_Rules">
        <test-method status="PASS" signature="setup()[pri:0, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="setup" is-config="true" duration-ms="68" started-at="2021-04-08T19:38:03Z" finished-at="2021-04-08T19:38:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="getTheListOfRulesForARevision_status200()[pri:1, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="getTheListOfRulesForARevision_status200" duration-ms="3806" started-at="2021-04-08T19:38:03Z" finished-at="2021-04-08T19:38:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTheListOfRulesForARevision_status200 -->
        <test-method status="PASS" signature="postCreateANewRuleSet_status200()[pri:2, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="postCreateANewRuleSet_status200" duration-ms="2048" started-at="2021-04-08T19:38:07Z" finished-at="2021-04-08T19:38:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCreateANewRuleSet_status200 -->
        <test-method status="PASS" signature="postCreateANewRuleSet_status400()[pri:3, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="postCreateANewRuleSet_status400" duration-ms="1650" started-at="2021-04-08T19:38:09Z" finished-at="2021-04-08T19:38:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCreateANewRuleSet_status400 -->
        <test-method status="FAIL" signature="postCreateANewRuleSet_status409()[pri:4, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="postCreateANewRuleSet_status409" duration-ms="2051" started-at="2021-04-08T19:38:10Z" finished-at="2021-04-08T19:38:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [409] but found [500]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [409] but found [500]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at restassured.automation.testcases.Restassured_Automation_Rules.postCreateANewRuleSet_status409(Restassured_Automation_Rules.java:354)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCreateANewRuleSet_status409 -->
        <test-method status="FAIL" signature="putUpdateANewRuleSet_status200()[pri:5, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="putUpdateANewRuleSet_status200" duration-ms="2030" started-at="2021-04-08T19:38:13Z" finished-at="2021-04-08T19:38:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [500]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [500]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at restassured.automation.testcases.Restassured_Automation_Rules.putUpdateANewRuleSet_status200(Restassured_Automation_Rules.java:455)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- putUpdateANewRuleSet_status200 -->
        <test-method status="PASS" signature="putUpdateANewRuleSet_status400()[pri:6, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="putUpdateANewRuleSet_status400" duration-ms="2056" started-at="2021-04-08T19:38:15Z" finished-at="2021-04-08T19:38:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- putUpdateANewRuleSet_status400 -->
        <test-method status="FAIL" signature="putUpdateANewRuleSet_status409()[pri:7, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="putUpdateANewRuleSet_status409" duration-ms="2204" started-at="2021-04-08T19:38:17Z" finished-at="2021-04-08T19:38:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [409] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [409] but found [200]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at restassured.automation.testcases.Restassured_Automation_Rules.putUpdateANewRuleSet_status409(Restassured_Automation_Rules.java:660)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- putUpdateANewRuleSet_status409 -->
        <test-method status="PASS" signature="deleteARuleSet_status204()[pri:8, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="deleteARuleSet_status204" duration-ms="2102" started-at="2021-04-08T19:38:19Z" finished-at="2021-04-08T19:38:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteARuleSet_status204 -->
        <test-method status="FAIL" signature="deleteARuleSet_status400()[pri:9, instance:restassured.automation.testcases.Restassured_Automation_Rules@4e04a765]" name="deleteARuleSet_status400" duration-ms="1561" started-at="2021-04-08T19:38:21Z" finished-at="2021-04-08T19:38:23Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 0, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at restassured.automation.testcases.Restassured_Automation_Rules.deleteARuleSet_status400(Restassured_Automation_Rules.java:781)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteARuleSet_status400 -->
      </class> <!-- restassured.automation.testcases.Restassured_Automation_Rules -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
