<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LT-CHN-33875" name="restassured.automation.testcases.Restassured_Automation_MethodologItem" tests="21" failures="4" timestamp="12 May 2021 06:54:25 GMT" time="95.152" errors="0">
  <testcase name="MethodologyItem_PostCreateANewMethodologyItemWithinTheMethodologyTree_status404" time="3.342" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_getAllMethodologyItemsForARevision_status404" time="3.332" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_GetAllMethodologyItemsForARevision_status400" time="3.326" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at restassured.automation.testcases.Restassured_Automation_MethodologItem.MethodologyItem_GetAllMethodologyItemsForARevision_status400(Restassured_Automation_MethodologItem.java:152)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MethodologyItem_GetAllMethodologyItemsForARevision_status400 -->
  <testcase name="MethodologyItem_PutMoveATreeItemToAFolderAtSpecifiedIndex_status400" time="4.672" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_UpdateItemsWorkFlowWithStatus_400" time="5.036" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_PutMoveATreeItemToAFolderAtSpecifiedIndex_status204" time="4.703" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_PostInitialiseAWorkProgram_status404" time="4.524" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_PatchUpdateAMethodologyItemForTheRevision_status204" time="4.549" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem">
    <failure type="java.lang.AssertionError" message="expected [204] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [204] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at restassured.automation.testcases.Restassured_Automation_MethodologItem.MethodologyItem_PatchUpdateAMethodologyItemForTheRevision_status204(Restassured_Automation_MethodologItem.java:634)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MethodologyItem_PatchUpdateAMethodologyItemForTheRevision_status204 -->
  <testcase name="MethodologyItem_PostCreateANewMethodologyItemWithinTheMethodologyTree_status200" time="3.527" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_UpdateItemsWorkFlowWithStatus_204" time="5.028" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_PostCreateANewMethodologyItemWithinTheMethodologyTree_status400" time="3.334" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_PutMoveATreeItemToAFolderAtSpecifiedIndex_status409" time="4.677" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem">
    <failure type="java.lang.AssertionError" message="expected [409] but found [204]">
      <![CDATA[java.lang.AssertionError: expected [409] but found [204]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at restassured.automation.testcases.Restassured_Automation_MethodologItem.MethodologyItem_PutMoveATreeItemToAFolderAtSpecifiedIndex_status409(Restassured_Automation_MethodologItem.java:562)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MethodologyItem_PutMoveATreeItemToAFolderAtSpecifiedIndex_status409 -->
  <testcase name="MethodologyItem_EndToEnd_Scenario" time="7.168" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem">
    <failure type="java.lang.AssertionError" message="expected [null] but found [max-age=63072000; includeSubDomains; preload]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [max-age=63072000; includeSubDomains; preload]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at restassured.automation.utils.Restassured_Automation_Utils.validate_HTTPStrictTransportSecurity(Restassured_Automation_Utils.java:347)
at restassured.automation.testcases.Restassured_Automation_MethodologItem.MethodologyItem_EndToEnd_Scenario(Restassured_Automation_MethodologItem.java:1389)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MethodologyItem_EndToEnd_Scenario -->
  <testcase name="MethodologyItem_PatchUpdateAMethodologyItemForTheRevision_status404" time="4.749" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_PostInitialiseAWorkProgram_status400" time="4.556" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_PatchUpdateAMethodologyItemForTheRevision_status400" time="4.567" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_GetAllMethodologyItemsForARevision_status200" time="3.930" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_UpdateItemsWorkFlowWithStatus_404" time="5.015" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_DeleteMarkAnItemAsDeleted_status400" time="5.882" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_PostInitialiseAWorkProgram_status204" time="4.561" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
  <testcase name="MethodologyItem_DeleteMarkAnItemAsDeleted_status200" time="4.674" classname="restassured.automation.testcases.Restassured_Automation_MethodologItem"/>
</testsuite> <!-- restassured.automation.testcases.Restassured_Automation_MethodologItem -->
