<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LT-CHN-33875" name="restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations" tests="11" failures="2" timestamp="13 Jun 2021 05:54:55 GMT" time="356.562" errors="0">
  <testcase name="MethodologyItemRelation_DeleteLinkedMethodologyItem_status400" time="52.387" classname="restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations"/>
  <testcase name="MethodologyItemRelation_PostCreateANewMethodologyRelation_status400" time="42.640" classname="restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations"/>
  <testcase name="MethodologyItemRelation_MethodologyItemRelation_EndToEnd_Scenario" time="24.365" classname="restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations"/>
  <testcase name="MethodologyItemRelation_ListOfAllMethodologyRelation_status200" time="8.436" classname="restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations"/>
  <testcase name="MethodologyItemRelation_UpdateAMethodologyRelation_status200" time="43.118" classname="restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations"/>
  <testcase name="MethodologyItemRelation_DeleteAnMethodologyRelation_status204" time="17.649" classname="restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations"/>
  <testcase name="MethodologyItemRelation_UpdateAMethodologyRelation_status400" time="45.899" classname="restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations"/>
  <testcase name="MethodologyItemRelation_PostCreateANewMethodologyRelation_status200" time="42.003" classname="restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations"/>
  <testcase name="MethodologyItemRelation_ListOfAllMethodologyRelation_status400" time="8.389" classname="restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations.MethodologyItemRelation_ListOfAllMethodologyRelation_status400(Restassured_Automation_MethodologyItemRelations.java:690)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MethodologyItemRelation_ListOfAllMethodologyRelation_status400 -->
  <testcase name="MethodologyItemRelation_DeleteLinkedMethodologyItem_status200" time="49.971" classname="restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations"/>
  <testcase name="MethodologyItemRelation_DeleteAnMethodologyRelation_status400" time="21.705" classname="restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations.MethodologyItemRelation_DeleteAnMethodologyRelation_status400(Restassured_Automation_MethodologyItemRelations.java:1493)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MethodologyItemRelation_DeleteAnMethodologyRelation_status400 -->
</testsuite> <!-- restassured.automation.testcases.Restassured_Automation_MethodologyItemRelations -->
